#!/bin/bash

# Copyright (C) 2017  Mikel Artetxe <artetxem@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$#" -ne 2 ]; then
    echo "USAGE: align src.tok.txt trg.tok.txt"
    exit 1
fi

TMP=`mktemp -d`
paste -d ' ||| ' $1 /dev/null /dev/null /dev/null /dev/null $2 > $TMP/corpus.tsv
$DIR/third-party/fast_align/build/fast_align -i $TMP/corpus.tsv -d -o -v > $TMP/forward.align
$DIR/third-party/fast_align/build/fast_align -i $TMP/corpus.tsv -d -o -v -r > $TMP/reverse.align
$DIR/third-party/fast_align/build/atools -i $TMP/forward.align -j $TMP/reverse.align -c grow-diag-final-and
rm -r $TMP
