#!/bin/bash

# Copyright (C) 2017  Mikel Artetxe <artetxem@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

sed -e "s/\`/'/g" | \
sed -e "s/´/'/g" | \
sed -e "s/‘/'/g" | \
sed -e "s/ ' ' / \" /g" | \
sed -e "s/\([[:digit:]]\) : \([[:digit:]]\)/\1:\2/g" | \
sed -e 's/\([lL]\) · \([lL]\)/\1·\2/g' | \
sed -e "s/\b\([[:alnum:]]\) ' \([[:alnum:]]\)/\1'\2/g" | \
sed -e "s/\([[:alnum:]]\) ' \([[:alnum:]]\)\b/\1'\2/g" | \
sed -e 's/~ ~ ~ //g' | \
perl $DIR/third-party/moses/replace-unicode-punctuation.perl | \
perl $DIR/third-party/moses/detruecase.perl | \
sed -e 's/^\s*//' | \
sed -e 's/\s*$//' | \
sed -e 's/^$/./'
